- name : DEMO on variables from files
  hosts : DEV
  vars_files :
    - db-variables.yaml
  tasks :
    - name : printing variables from files
      debug :
        msg : "IP address = {{IP}}"