- name : DEMO on register variables
  hosts : DEV
  tasks :
    - name : register the variables
      shell : pwd
      register : out

    - name : print the out value
      debug :
        msg : "{{out.stdout}}"